### ISSUE TITLE
Error: Job name "@example/command-runner:command" does not exist

### ISSUE THREAD

**Issue by sonukapoor** [mgechev/cli-builders-demo#1]
When I try to run the tests within the `command-builder` folder using `npm run test`, I get the following error:
```
> @example/command-runner@1.0.0 test C:\projects\cli-builders-demo\command-builder
> ts-node node_modules/jasmine/bin/jasmine command/index_spec.ts

Randomized with seed 79078
Started
F

Failures:
1) Command Runner Builder can run node
  Message:
    Error: Job name "@example/command-runner:command" does not exist.
  Stack:
    Error: Job name "@example/command-runner:command" does not exist.
        at SwitchMapSubscriber.description.handler.pipe.operators_1.switchMap.handler [as project] (C:\projects\cli-builders-demo\command-builder\node_modules\@angular-devkit\core\src\experimental\jobs\simple-scheduler.js:292:27)
        at SwitchMapSubscriber._next (C:\projects\cli-builders-demo\command-builder\node_modules\rxjs\src\internal\operators\switchMap.ts:106:21)
        at SwitchMapSubscriber.Subscriber.next (C:\projects\cli-builders-demo\command-builder\node_modules\rxjs\src\internal\Subscriber.ts:99:12)
        at SwitchMapSubscriber.notifyNext (C:\projects\cli-builders-demo\command-builder\node_modules\rxjs\src\internal\operators\switchMap.ts:149:24)
        at InnerSubscriber._next (C:\projects\cli-builders-demo\command-builder\node_modules\rxjs\src\internal\InnerSubscriber.ts:17:17)
        at InnerSubscriber.Subscriber.next (C:\projects\cli-builders-demo\command-builder\node_modules\rxjs\src\internal\Subscriber.ts:99:12)
        at C:\projects\cli-builders-demo\command-builder\node_modules\rxjs\src\internal\util\subscribeTo.ts:18:20
        at Object.subscribeToResult (C:\projects\cli-builders-demo\command-builder\node_modules\rxjs\src\internal\util\subscribeToResult.ts:25:29)
        at SwitchMapSubscriber._innerSub (C:\projects\cli-builders-demo\command-builder\node_modules\rxjs\src\internal\operators\switchMap.ts:122:30)
        at SwitchMapSubscriber._next (C:\projects\cli-builders-demo\command-builder\node_modules\rxjs\src\internal\operators\switchMap.ts:111:10)

1 spec, 1 failure
```

Any idea what I am missing here? No changes were done to the code.

**Comment by benwinding** [comment]
I'm also getting this error...

Amazing that this is repository is linked from the official docs and it doesn't work....
